name: example
description: ''
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.8.0

dependencies:
  yaml_variable_scanner:
    path: ../
  io: ^1.0.5
  args: ^2.7.0

dev_dependencies:
  lints: any