name: example
description: ''
publish_to: none
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  yaml_variable_scanner:
    path: ../
  io: ^1.0.4
  args: ^2.4.2

dev_dependencies:
  lints: any