name: yaml_variable_scanner
description: ''
publish_to: none
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  yaml: ^3.1.2
  glob: ^2.1.2
  console: ^4.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2