name: yaml_variable_scanner
description: >-
  YAML Variable Scanner,
  used to scan multiple files for text that can use YAML variables.
version: 0.0.7
repository: https://github.com/AmosHuKe/yaml_variable_scanner
issue_tracker: https://github.com/AmosHuKe/yaml_variable_scanner/issues

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  yaml: ^3.1.0
  glob: ^2.1.0
  console: ^4.1.0

dev_dependencies:
  lints: any
  test: any